# Generated by Django 3.2.13 on 2022-06-23 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anvil_consortium_manager', '0007_groupaccountmembership_account_historicforeignkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('consent', models.CharField(max_length=255, unique=True)),
                ('data_use_limitations', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ResearchCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=15, unique=True)),
                ('full_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('consent_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anvil_access.consentgroup')),
                ('research_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anvil_access.researchcenter')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anvil_consortium_manager.workspace')),
            ],
        ),
        migrations.AddConstraint(
            model_name='workspacedata',
            constraint=models.UniqueConstraint(fields=('research_center', 'consent_group', 'version'), name='unique_workspace_data'),
        ),
    ]
