# Generated by Django 3.2.13 on 2022-06-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacedata',
            name='version',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='workspacedata',
            constraint=models.CheckConstraint(check=models.Q(('version__gt', 0)), name='positive_version'),
        ),
    ]
