# Generated by Django 3.2.13 on 2022-06-22 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0007_groupaccountmembership_account_historicforeignkey'),
        ('anvil_access', '0002_researchcenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anvil_access.consentgroup')),
                ('research_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anvil_access.researchcenter')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anvil_consortium_manager.workspace')),
            ],
        ),
        migrations.AddConstraint(
            model_name='workspacedata',
            constraint=models.UniqueConstraint(fields=('research_center', 'consent_group'), name='unique_workspace_data'),
        ),
    ]
