# Generated by Django 3.2.13 on 2022-06-23 23:03

from django.db import migrations, models
import gregor_django.anvil_access.models


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_access', '0002_workspacedata_version_positive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacedata',
            name='version',
            field=models.PositiveIntegerField(validators=[gregor_django.anvil_access.models.validate_gt_0]),
        ),
    ]
