# Generated by Django 3.2.13 on 2022-06-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_access', '0003_auto_20220622_1507'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workspacedata',
            name='unique_workspace_data',
        ),
        migrations.AddField(
            model_name='workspacedata',
            name='version',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='workspacedata',
            constraint=models.UniqueConstraint(fields=('research_center', 'consent_group', 'version'), name='unique_workspace_data'),
        ),
    ]
