# Generated by Django 3.2.15 on 2022-09-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregor_anvil', '0001_initial'),
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='research_centers',
            field=models.ManyToManyField(to='gregor_anvil.ResearchCenter'),
        ),
    ]
