# Generated by Django 3.2.16 on 2023-04-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregor_anvil', '0008_historicalpartnergroup_partnergroup'),
        ('users', '0003_user_research_centers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='partner_groups',
            field=models.ManyToManyField(to='gregor_anvil.PartnerGroup'),
        ),
    ]
