# Generated by Django 3.2.16 on 2023-05-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregor_anvil', '0009_unique_full_names'),
        ('users', '0004_user_partner_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='partner_groups',
            field=models.ManyToManyField(blank=True, to='gregor_anvil.PartnerGroup'),
        ),
        migrations.AlterField(
            model_name='user',
            name='research_centers',
            field=models.ManyToManyField(blank=True, to='gregor_anvil.ResearchCenter'),
        ),
    ]
