# Generated by Django 3.2.13 on 2022-07-18 23:30

from django.db import migrations, models
import django.db.models.deletion
import gregor_django.gregor_anvil.models


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0008_workspacegroupaccess_cancompute'),
        ('gregor_anvil', '0002_researchcenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(validators=[gregor_django.gregor_anvil.models.validate_gt_0])),
                ('consent_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gregor_anvil.consentgroup')),
                ('research_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gregor_anvil.researchcenter')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anvil_consortium_manager.workspace')),
            ],
        ),
        migrations.AddConstraint(
            model_name='uploadworkspace',
            constraint=models.UniqueConstraint(fields=('research_center', 'consent_group', 'version'), name='unique_workspace_data'),
        ),
        migrations.AddConstraint(
            model_name='uploadworkspace',
            constraint=models.CheckConstraint(check=models.Q(('version__gt', 0)), name='positive_version'),
        ),
    ]
