# Generated by Django 3.2.16 on 2023-03-23 23:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0008_workspace_is_locked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gregor_anvil', '0006_combinedconsortiumdataworkspace_historicalcombinedconsortiumdataworkspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('full_data_use_limitations', models.TextField(help_text='The full data use limitations for this workspace.')),
                ('release_date', models.DateField(blank=True, help_text='Date that this workspace was released to the scientific community.', null=True)),
                ('version', models.IntegerField(help_text='Version of the release (should be the same as dbGaP version).', validators=[django.core.validators.MinValueValidator(1)])),
                ('dbgap_participant_set', models.IntegerField(help_text='dbGaP participant set of the workspace', validators=[django.core.validators.MinValueValidator(1)])),
                ('consent_group', models.ForeignKey(help_text='Consent group for the data in this workspace.', on_delete=django.db.models.deletion.PROTECT, to='gregor_anvil.consentgroup')),
                ('upload_workspaces', models.ManyToManyField(help_text='Upload workspaces contributing data to this workspace.', to='gregor_anvil.UploadWorkspace')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anvil_consortium_manager.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalReleaseWorkspace',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('full_data_use_limitations', models.TextField(help_text='The full data use limitations for this workspace.')),
                ('release_date', models.DateField(blank=True, help_text='Date that this workspace was released to the scientific community.', null=True)),
                ('version', models.IntegerField(help_text='Version of the release (should be the same as dbGaP version).', validators=[django.core.validators.MinValueValidator(1)])),
                ('dbgap_participant_set', models.IntegerField(help_text='dbGaP participant set of the workspace', validators=[django.core.validators.MinValueValidator(1)])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('consent_group', models.ForeignKey(blank=True, db_constraint=False, help_text='Consent group for the data in this workspace.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gregor_anvil.consentgroup')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='anvil_consortium_manager.workspace')),
            ],
            options={
                'verbose_name': 'historical release workspace',
                'verbose_name_plural': 'historical release workspaces',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='releaseworkspace',
            constraint=models.UniqueConstraint(fields=('consent_group', 'version'), name='unique_release_workspace'),
        ),
    ]
