# Generated by Django 3.2.16 on 2023-03-24 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gregor_anvil', '0007_auto_20230323_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalreleaseworkspace',
            old_name='version',
            new_name='dbgap_version',
        ),
        migrations.RenameField(
            model_name='releaseworkspace',
            old_name='version',
            new_name='dbgap_version',
        ),
    ]
