# Generated by Django 3.2.16 on 2023-03-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregor_anvil', '0008_auto_20230324_1633'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='releaseworkspace',
            name='unique_release_workspace',
        ),
        migrations.AddConstraint(
            model_name='releaseworkspace',
            constraint=models.UniqueConstraint(fields=('consent_group', 'dbgap_version'), name='unique_release_workspace'),
        ),
    ]
