# Generated by Django 3.2.19 on 2023-06-13 18:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gregor_anvil', '0009_unique_full_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('cycle', models.PositiveIntegerField(help_text='The upload cycle represented by this model.', unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('start_date', models.DateField(help_text='The start date of this upload cycle.')),
                ('end_date', models.DateField(help_text='The end date of this upload cycle.')),
                ('note', models.TextField(blank=True, help_text='Additional notes.')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalUploadCycle',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('cycle', models.PositiveIntegerField(db_index=True, help_text='The upload cycle represented by this model.', validators=[django.core.validators.MinValueValidator(1)])),
                ('start_date', models.DateField(help_text='The start date of this upload cycle.')),
                ('end_date', models.DateField(help_text='The end date of this upload cycle.')),
                ('note', models.TextField(blank=True, help_text='Additional notes.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical upload cycle',
                'verbose_name_plural': 'historical upload cycles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
