# Generated by Django 3.2.16 on 2023-03-27 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gregor_anvil', '0009_auto_20230324_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalreleaseworkspace',
            old_name='release_date',
            new_name='date_released',
        ),
        migrations.RenameField(
            model_name='releaseworkspace',
            old_name='release_date',
            new_name='date_released',
        ),
    ]
