# Generated by Django 3.2.19 on 2023-06-14 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gregor_anvil', '0010_historicaluploadcycle_uploadcycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinedconsortiumdataworkspace',
            name='upload_cycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gregor_anvil.uploadcycle'),
        ),
        migrations.AddField(
            model_name='historicalcombinedconsortiumdataworkspace',
            name='upload_cycle',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gregor_anvil.uploadcycle'),
        ),
        migrations.AddField(
            model_name='historicalreleaseworkspace',
            name='upload_cycle',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gregor_anvil.uploadcycle'),
        ),
        migrations.AddField(
            model_name='historicaluploadworkspace',
            name='upload_cycle',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gregor_anvil.uploadcycle'),
        ),
        migrations.AddField(
            model_name='releaseworkspace',
            name='upload_cycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gregor_anvil.uploadcycle'),
        ),
        migrations.AddField(
            model_name='uploadworkspace',
            name='upload_cycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gregor_anvil.uploadcycle'),
        ),
    ]
