# Generated by Django 3.2.16 on 2023-03-27 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregor_anvil', '0010_auto_20230327_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreleaseworkspace',
            name='dbgap_participant_set',
            field=models.IntegerField(help_text='dbGaP participant set of the workspace', validators=[django.core.validators.MinValueValidator(1)], verbose_name=' dbGaP participant set'),
        ),
        migrations.AlterField(
            model_name='historicalreleaseworkspace',
            name='dbgap_version',
            field=models.IntegerField(help_text='Version of the release (should be the same as dbGaP version).', validators=[django.core.validators.MinValueValidator(1)], verbose_name=' dbGaP version'),
        ),
        migrations.AlterField(
            model_name='releaseworkspace',
            name='dbgap_participant_set',
            field=models.IntegerField(help_text='dbGaP participant set of the workspace', validators=[django.core.validators.MinValueValidator(1)], verbose_name=' dbGaP participant set'),
        ),
        migrations.AlterField(
            model_name='releaseworkspace',
            name='dbgap_version',
            field=models.IntegerField(help_text='Version of the release (should be the same as dbGaP version).', validators=[django.core.validators.MinValueValidator(1)], verbose_name=' dbGaP version'),
        ),
    ]
