# Generated by Django 3.2.19 on 2023-08-07 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gregor_anvil', '0016_remove_combinedconsortiumdataworkspace_upload_workspaces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releaseworkspace',
            name='upload_workspaces',
        ),
    ]
