# Generated by Django 3.2.19 on 2023-07-10 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gregor_anvil', '0017_auto_20230710_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dccprocessingworkspace',
            name='upload_cycle',
            field=models.ForeignKey(help_text='Upload cycle associated with this workspace.', on_delete=django.db.models.deletion.PROTECT, to='gregor_anvil.uploadcycle'),
        ),
    ]
