# Generated by Django 4.2.9 on 2024-02-07 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gregor_anvil", "0019_historicalexchangeworkspace_exchangeworkspace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangeworkspace",
            name="research_center",
            field=models.OneToOneField(
                help_text="The ResearchCenter associated with this workspace.",
                on_delete=django.db.models.deletion.PROTECT,
                to="gregor_anvil.researchcenter",
            ),
        ),
    ]
