# Generated by Django 4.2.11 on 2024-04-25 22:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("anvil_consortium_manager", "0015_add_new_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gregor_anvil", "0020_alter_exchangeworkspace_research_center"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HistoricalExampleWorkspace",
            new_name="HistoricalResourceWorkspace",
        ),
        migrations.RenameModel(
            old_name="ExampleWorkspace",
            new_name="ResourceWorkspace",
        ),
        migrations.AlterModelOptions(
            name="historicalresourceworkspace",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical resource workspace",
                "verbose_name_plural": "historical resource workspaces",
            },
        ),
    ]
