# Generated by Django 4.2.11 on 2024-04-25 22:17


from django.db import migrations


def workspace_type_example_to_resource(apps, schema_editor):
    """Change the workspace type from "example" to "resource"."""
    Workspace = apps.get_model("anvil_consortium_manager", "Workspace")

    for row in Workspace.objects.filter(workspace_type="example"):
        row.workspace_type = "resource"
        row.save(update_fields=["workspace_type"])


def workspace_type_resource_to_example(apps, schema_editor):
    """Change the workspace type from "resource" to "example"."""
    Workspace = apps.get_model("anvil_consortium_manager", "Workspace")

    for row in Workspace.objects.filter(workspace_type="resource"):
        row.workspace_type = "example"
        row.save(update_fields=["workspace_type"])


class Migration(migrations.Migration):

    dependencies = [
        ('gregor_anvil', '0021_rename_exampleworkspace_to_resourceworkspace'),
    ]

    operations = [
        migrations.RunPython(workspace_type_example_to_resource, reverse_code=workspace_type_resource_to_example),
    ]
