# Generated by Django 4.2.11 on 2024-04-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gregor_anvil", "0022_update_exampleworkspace_workspace_type_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalresourceworkspace",
            name="brief_description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resourceworkspace",
            name="brief_description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
