# Generated by Django 4.2.11 on 2024-05-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregor_anvil', '0023_resourceworkspace_add_brief_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpartnergroup',
            name='drupal_node_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalresearchcenter',
            name='drupal_node_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnergroup',
            name='drupal_node_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchcenter',
            name='drupal_node_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
