# Generated by Django 4.2.13 on 2024-07-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregor_anvil', '0024_member_upload_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpartnergroup',
            name='drupal_node_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalresearchcenter',
            name='drupal_node_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnergroup',
            name='drupal_node_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchcenter',
            name='drupal_node_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
