# Generated by Django 4.2.14 on 2024-08-01 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gregor_anvil', '0024_member_upload_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalreleaseworkspace',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical release prep workspace', 'verbose_name_plural': 'historical release prep workspaces'},
        ),
        migrations.AlterModelOptions(
            name='releaseworkspace',
            options={'verbose_name': 'release prep workspace'},
        ),
    ]
