# Generated by Django 4.2.13 on 2024-07-09 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0019_accountuserarchive'),
        ('gregor_anvil', '0024_historicalresearchcenter_member_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpartnergroup',
            name='member_group',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The AnVIL group containing members from this Partner Group.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='anvil_consortium_manager.managedgroup'),
        ),
        migrations.AddField(
            model_name='historicalpartnergroup',
            name='uploader_group',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The group that has write/upload access to workspaces associated with this Partner Group.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='anvil_consortium_manager.managedgroup'),
        ),
        migrations.AddField(
            model_name='partnergroup',
            name='member_group',
            field=models.OneToOneField(help_text='The AnVIL group containing members from this Partner Group.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_group_of_members', to='anvil_consortium_manager.managedgroup'),
        ),
        migrations.AddField(
            model_name='partnergroup',
            name='uploader_group',
            field=models.OneToOneField(help_text='The group that has write/upload access to workspaces associated with this Partner Group.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_group_of_uploaders', to='anvil_consortium_manager.managedgroup'),
        ),
    ]
