# Generated by Django 4.2.15 on 2024-08-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregor_anvil', '0025_releaseworkspace_meta_change_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpartnergroup',
            name='drupal_node_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalresearchcenter',
            name='drupal_node_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnergroup',
            name='drupal_node_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchcenter',
            name='drupal_node_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
