# Generated by Django 4.2.15 on 2024-08-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregor_anvil', '0026_historicalpartnergroup_drupal_node_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluploadcycle',
            name='is_ready_for_compute',
            field=models.BooleanField(default=False, help_text='Boolean indicator of whether workspace writers should be able to run compute.'),
        ),
        migrations.AddField(
            model_name='uploadcycle',
            name='is_ready_for_compute',
            field=models.BooleanField(default=False, help_text='Boolean indicator of whether workspace writers should be able to run compute.'),
        ),
    ]
