# Generated by Django 4.2.15 on 2024-08-27 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gregor_anvil", "0027_tracking_fields_for_custom_audits"),
    ]

    operations = []
