# Generated by Django 4.2.15 on 2024-08-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregor_anvil', '0027_uploadcycle_is_ready_for_compute'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluploadworkspace',
            name='date_qc_completed',
            field=models.DateTimeField(blank=True, default=None, help_text='Date that QC was completed for this workspace. If null, QC is not complete.', null=True),
        ),
        migrations.AddField(
            model_name='uploadworkspace',
            name='date_qc_completed',
            field=models.DateTimeField(blank=True, default=None, help_text='Date that QC was completed for this workspace. If null, QC is not complete.', null=True),
        ),
    ]
