# Generated by Django 4.2.15 on 2024-08-27 22:05

from datetime import timedelta

from django.db import migrations
from django.utils import timezone

def populate_combinedworkspace_date_completed(apps, schema_editor):
    CombinedConsortiumDataWorkspace = apps.get_model("gregor_anvil", "CombinedConsortiumDataWorkspace")
    WorkspaceGroupSharing = apps.get_model("anvil_consortium_manager", "WorkspaceGroupSharing")
    # Create one UploadWorkspace for each unique version.
    for row in CombinedConsortiumDataWorkspace.objects.all():
        try:
            workspace_group_sharing = WorkspaceGroupSharing.objects.get(
                workspace=row.workspace,
                group=row.workspace.authorization_domains.first(),
            )
        except WorkspaceGroupSharing.DoesNotExist:
            continue
        else:
            row.date_completed = workspace_group_sharing.created.date()
            row.full_clean()
            row.save(update_fields=["date_completed"])


class Migration(migrations.Migration):

    dependencies = [
        ("gregor_anvil", "0029_populate_uploadworkspace_date_qc_completed"),
    ]

    operations = [
        migrations.RunPython(populate_combinedworkspace_date_completed, reverse_code=migrations.RunPython.noop),
    ]
