# Generated by Django 4.2.15 on 2024-08-20 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0019_accountuserarchive'),
        ('gregor_anvil', '0029_consortiumcombineddataworkspace_date_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalresearchcenter',
            name='non_member_group',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The AnVIL group containing non-members from this Research Center.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='anvil_consortium_manager.managedgroup'),
        ),
        migrations.AddField(
            model_name='researchcenter',
            name='non_member_group',
            field=models.OneToOneField(blank=True, help_text='The AnVIL group containing non-members from this Research Center.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='research_center_of_non_members', to='anvil_consortium_manager.managedgroup'),
        ),
    ]
