# Generated by Django 4.2.15 on 2024-08-27 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gregor_anvil", "0029_populate_uploadworkspace_date_qc_complete"),
    ]

    operations = []
