# Generated by Django 4.2.20 on 2025-04-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregor_anvil', '0030_populate_consortiumcombineddataworkspace_date_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpartnergroup',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='partnergroup',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
