# Generated by Django 4.2.15 on 2024-08-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregor_anvil', '0030_researchcenter_non_member_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluploadcycle',
            name='is_ready_for_compute',
        ),
        migrations.RemoveField(
            model_name='uploadcycle',
            name='is_ready_for_compute',
        ),
        migrations.AddField(
            model_name='historicaluploadcycle',
            name='date_ready_for_compute',
            field=models.DateField(blank=True, default=None, help_text='Date that this workspace was ready for RC uploaders to run compute.', null=True),
        ),
        migrations.AddField(
            model_name='uploadcycle',
            name='date_ready_for_compute',
            field=models.DateField(blank=True, default=None, help_text='Date that this workspace was ready for RC uploaders to run compute.', null=True),
        ),
    ]
