# Generated by Django 4.2.22 on 2025-07-09 18:33

from django.db import migrations, models
import gregor_django.gregor_anvil.models


class Migration(migrations.Migration):

    dependencies = [
        ('gregor_anvil', '0032_alter_historicalpartnergroup_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinedconsortiumdataworkspace',
            name='date_completed',
            field=models.DateField(blank=True, default=None, help_text='Date that data preparation in this workspace was completed.', null=True, validators=[gregor_django.gregor_anvil.models.validate_not_future_date]),
        ),
        migrations.AlterField(
            model_name='historicalcombinedconsortiumdataworkspace',
            name='date_completed',
            field=models.DateField(blank=True, default=None, help_text='Date that data preparation in this workspace was completed.', null=True, validators=[gregor_django.gregor_anvil.models.validate_not_future_date]),
        ),
        migrations.AlterField(
            model_name='historicalpartneruploadworkspace',
            name='date_completed',
            field=models.DateField(blank=True, help_text='The date when uploads to this workspace and data validation were completed.', null=True, validators=[gregor_django.gregor_anvil.models.validate_not_future_date]),
        ),
        migrations.AlterField(
            model_name='historicalreleaseworkspace',
            name='date_released',
            field=models.DateField(blank=True, help_text='Date that this workspace was released to the scientific community.', null=True, validators=[gregor_django.gregor_anvil.models.validate_not_future_date]),
        ),
        migrations.AlterField(
            model_name='historicaluploadcycle',
            name='date_ready_for_compute',
            field=models.DateField(blank=True, default=None, help_text='Date that this workspace was ready for RC uploaders to run compute.', null=True, validators=[gregor_django.gregor_anvil.models.validate_not_future_date]),
        ),
        migrations.AlterField(
            model_name='historicaluploadworkspace',
            name='date_qc_completed',
            field=models.DateField(blank=True, default=None, help_text='Date that QC was completed for this workspace. If null, QC is not complete.', null=True, validators=[gregor_django.gregor_anvil.models.validate_not_future_date]),
        ),
        migrations.AlterField(
            model_name='partneruploadworkspace',
            name='date_completed',
            field=models.DateField(blank=True, help_text='The date when uploads to this workspace and data validation were completed.', null=True, validators=[gregor_django.gregor_anvil.models.validate_not_future_date]),
        ),
        migrations.AlterField(
            model_name='releaseworkspace',
            name='date_released',
            field=models.DateField(blank=True, help_text='Date that this workspace was released to the scientific community.', null=True, validators=[gregor_django.gregor_anvil.models.validate_not_future_date]),
        ),
        migrations.AlterField(
            model_name='uploadcycle',
            name='date_ready_for_compute',
            field=models.DateField(blank=True, default=None, help_text='Date that this workspace was ready for RC uploaders to run compute.', null=True, validators=[gregor_django.gregor_anvil.models.validate_not_future_date]),
        ),
        migrations.AlterField(
            model_name='uploadworkspace',
            name='date_qc_completed',
            field=models.DateField(blank=True, default=None, help_text='Date that QC was completed for this workspace. If null, QC is not complete.', null=True, validators=[gregor_django.gregor_anvil.models.validate_not_future_date]),
        ),
    ]
