# Generated by Django 4.2.15 on 2024-08-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregor_anvil', '0032_alter_historicaluploadworkspace_date_qc_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinedconsortiumdataworkspace',
            name='date_completed',
            field=models.DateField(blank=True, default=None, help_text='Date that data preparation in this workspace was completed.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcombinedconsortiumdataworkspace',
            name='date_completed',
            field=models.DateField(blank=True, default=None, help_text='Date that data preparation in this workspace was completed.', null=True),
        ),
    ]
