# Generated by Django 4.2.23 on 2025-08-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregor_anvil', '0033_alter_combinedconsortiumdataworkspace_date_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseworkspace',
            name='contributing_dcc_processed_data_workspaces',
            field=models.ManyToManyField(blank=True, help_text='DCCProcessedDataWorkspaces with data tables contributing to this release.', related_name='release_workspaces', to='gregor_anvil.dccprocesseddataworkspace'),
        ),
        migrations.AddField(
            model_name='releaseworkspace',
            name='contributing_upload_workspaces',
            field=models.ManyToManyField(help_text='UploadWorkspaces with data tables contributing to this release. (Note that this does not include workspaces containing files contributing to this release.)', related_name='release_workspaces', to='gregor_anvil.uploadworkspace'),
        ),
    ]
