# Generated by Django 4.2.23 on 2025-08-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0019_accountuserarchive'),
        ('gregor_anvil', '0033_alter_combinedconsortiumdataworkspace_date_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseworkspace',
            name='contributing_workspaces',
            field=models.ManyToManyField(help_text='Workspaces with data tables contributing to this release. (Note that this does not include workspaces containing files contributing to this release.)', related_name='release_workspaces', to='anvil_consortium_manager.workspace'),
        ),
    ]
