# Generated by Django 5.2.11 on 2026-04-03 16:24

import django.core.validators
import django.db.models.deletion
import django_extensions.db.fields
import gregor_django.gregor_anvil.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0020_historicalworkspace_app_access_and_more'),
        ('gregor_anvil', '0034_releaseworkspace_contributing_workspaces'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRCProcessedDataWorkspace',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('version', models.IntegerField(help_text='The version of this workspace for this ResearchCenter and ConsentGroup.', validators=[django.core.validators.MinValueValidator(1)])),
                ('date_completed', models.DateField(blank=True, help_text='The date when uploads to this workspace and data validation were completed.', null=True, validators=[gregor_django.gregor_anvil.models.validate_not_future_date])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('consent_group', models.ForeignKey(blank=True, db_constraint=False, help_text='Consent group associated with this data.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gregor_anvil.consentgroup')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('research_center', models.ForeignKey(blank=True, db_constraint=False, help_text='ResearchCenter associated with this workspace.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gregor_anvil.researchcenter')),
                ('upload_cycle', models.ForeignKey(blank=True, db_constraint=False, help_text='Upload cycle associated with this workspace.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gregor_anvil.uploadcycle')),
                ('workspace', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='anvil_consortium_manager.workspace')),
            ],
            options={
                'verbose_name': 'historical rc processed data workspace',
                'verbose_name_plural': 'historical rc processed data workspaces',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RCProcessedDataWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('version', models.IntegerField(help_text='The version of this workspace for this ResearchCenter and ConsentGroup.', validators=[django.core.validators.MinValueValidator(1)])),
                ('date_completed', models.DateField(blank=True, help_text='The date when uploads to this workspace and data validation were completed.', null=True, validators=[gregor_django.gregor_anvil.models.validate_not_future_date])),
                ('consent_group', models.ForeignKey(help_text='Consent group associated with this data.', on_delete=django.db.models.deletion.PROTECT, to='gregor_anvil.consentgroup')),
                ('research_center', models.ForeignKey(help_text='ResearchCenter associated with this workspace.', on_delete=django.db.models.deletion.PROTECT, to='gregor_anvil.researchcenter')),
                ('upload_cycle', models.ForeignKey(blank=True, help_text='Upload cycle associated with this workspace.', null=True, on_delete=django.db.models.deletion.PROTECT, to='gregor_anvil.uploadcycle')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anvil_consortium_manager.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='releaseworkspace',
            name='contributing_rc_processed_data_workspaces',
            field=models.ManyToManyField(blank=True, help_text='RCProcessedDataWorkspaces with data tables contributing to this release.', related_name='release_workspaces', to='gregor_anvil.rcprocesseddataworkspace'),
        ),
        migrations.AddConstraint(
            model_name='rcprocesseddataworkspace',
            constraint=models.UniqueConstraint(fields=('research_center', 'consent_group', 'version'), name='unique_rc_processed_data_workspace'),
        ),
    ]
