# Generated by Django 5.2.14 on 2026-06-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregor_anvil', '0035_rc_processed_data_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinedconsortiumdataworkspace',
            name='contributing_dcc_processed_data_workspaces',
            field=models.ManyToManyField(blank=True, help_text='DCCProcessedDataWorkspaces with data tables contributing to this workspace.', related_name='combined_workspaces', to='gregor_anvil.dccprocesseddataworkspace'),
        ),
        migrations.AddField(
            model_name='combinedconsortiumdataworkspace',
            name='contributing_partner_upload_workspaces',
            field=models.ManyToManyField(blank=True, help_text='PartnerUploadWorkspaces with data tables contributing to this workspace.', related_name='combined_workspaces', to='gregor_anvil.partneruploadworkspace'),
        ),
        migrations.AddField(
            model_name='combinedconsortiumdataworkspace',
            name='contributing_rc_processed_data_workspaces',
            field=models.ManyToManyField(blank=True, help_text='RCProcessedDataWorkspaces with data tables contributing to this workspace.', related_name='combined_workspaces', to='gregor_anvil.rcprocesseddataworkspace'),
        ),
        migrations.AddField(
            model_name='combinedconsortiumdataworkspace',
            name='contributing_upload_workspaces',
            field=models.ManyToManyField(help_text='UploadWorkspaces with data tables contributing to this workspace. (Note that this does not include workspaces only containing files contributing to this workspace.)', related_name='combined_workspaces', to='gregor_anvil.uploadworkspace'),
        ),
    ]
