# Generated by Django 5.2.11 on 2026-03-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregor_anvil', '0035_historicalrcprocesseddataworkspace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseworkspace',
            name='contributing_rc_processed_data_workspaces',
            field=models.ManyToManyField(blank=True, help_text='RCProcessedDataWorkspaces with data tables contributing to this release.', related_name='release_workspaces', to='gregor_anvil.rcprocesseddataworkspace'),
        ),
    ]
